# Run this as a dev container with a source code volume connected to /app

FROM node:18-alpine AS development

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install --frozen-lockfile

ENTRYPOINT [ "npm", "run", "dev", "--" ]
