# Run this as a dev container with a source code volume connected to /app

FROM python:3.13

WORKDIR /app

COPY requirements.txt requirements.txt
RUN python -m pip install -r requirements.txt

CMD [ "python3", "main.py" ]
